---
title: "Notes for live demo of iteration and custom functions"

date-modified: 'today'
date-format: long

format: 
  html:
    footer: "CC BY 4.0 John R Little"

license: CC BY    
---

## Load library packages

```{r}
#| message: false
#| warning: false
library(tidyverse)
```

## Reference code

```{r}
gapminder::gapminder |> 
  ggplot(aes(year, pop)) +
  geom_line(aes(color = country), show.legend = FALSE) +
  facet_wrap(vars(continent))
  
```

```{r}
starwars |> 
  filter(mass < 500) |> 
  ggplot(aes(height, mass)) +
  geom_point(aes(color = gender)) +
  facet_wrap(vars(gender), nrow = 3)

starwars |> 
  filter(mass < 500) |> 
  filter(gender == "masculine") |> 
  ggplot(aes(height, mass)) +
  geom_point()  + geom_smooth(method = lm, se = FALSE)

starwars |> 
  filter(mass < 500) |> 
  filter(gender == "feminine") |> 
  ggplot(aes(height, mass)) +
  geom_point()

starwars |> 
  filter(mass < 500) |> 
  filter(is.na(gender)) |> 
  ggplot(aes(height, mass)) +
  geom_point() 

starwars |> 
  filter(mass < 500) |> 
  nest(data = -gender) |> 
  mutate(my_plot = map(data, ~ .x |> ggplot(aes(height, mass)) + geom_point())) |> 
  mutate(my_other_plot = map(data, make_plot)) |> 
  mutate(my_plot_title = map2(data, gender, ~ .x |> ggplot(aes(height, mass)) + geom_point() + ggtitle(.y))) |> 
  mutate(my_fit = map(data, ~ lm(mass ~ height, data = .x))) |> 
  mutate(my_fit_tidy = map(my_fit, broom::tidy)) |> 
  unnest(my_fit_tidy) |> 
  filter(term != "(Intercept)") |> 
  filter(p.value < 0.5)
  
  pull(my_plot_title)
```

### Custom function

`Alt + Ctrl + x`

```{r}
make_plot <- function(my_df) {
  my_df |> 
    ggplot(aes(height, mass)) +
    geom_point()
}
```

```{r}
starwars |> 
  select(name) |> 
  mutate(key = str_to_lower(name)) |> 
  mutate(key = str_replace_all(key, " ", "_"))

make_key <- function(my_df, my_var) {
  my_df |> 
    select({{my_var}}) |> 
    mutate(key = str_to_upper({{my_var}})) |> 
    mutate(key = str_replace_all(key, " ", "_")) |> 
    mutate(first_letter = str_extract({{my_var}}, "^\\w"))
}

starwars |> 
  make_key(name)

starwars |> 
  make_key(hair_color)

babynames::babynames |> 
  make_key(name)

economics_long |> 
  make_key(variable)
```
