project:
  type: website

website:
  title: "Intro2r: CommSci @ USC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: import.qmd
        text: Import/Wrangle/Viz
      - href: tidy_tuesday_itra.qmd
        text: Example EDA
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

