project:
  type: website

website:
  title: "Intro2r: CommSci @ USC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: import.qmd
        text: Import/Wrangle
      - href: viz.qmd
        text: Visualization
      - text: lm/join/pivot
        menu:
          - text: regression
            href: regression.qmd
          - text: tall/wide
            href: longer_wider.qmd
          - text: join
            href: join.qmd
      - href: tidy_tuesday_itra.qmd
        text: Example EDA
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

